import Nav from '../components/Nav'
import Footer from '../components/Footer'

export const metadata = {
  title: 'Terms of Use',
  description: 'Terms of Use for Flight Levels products including ATC Clearance Trainer and Checkride Prep AI.',
}

export default function Terms() {
  return (
    <>
      <Nav />
      <main className="max-w-3xl mx-auto px-6 py-16 text-gray-800">
        <h1 className="text-3xl font-bold mb-2">Terms of Use</h1>
        <p className="text-sm text-gray-500 mb-10">Last updated: August 28, 2026</p>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
          <p>By accessing or using any Flight Levels product — including ATC Clearance Trainer and Checkride Prep AI (collectively, the "Service") — you agree to be bound by these Terms of Use. If you do not agree, do not use the Service.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">2. Description of Service</h2>
          <p>Flight Levels provides AI-powered aviation training tools for pilots. These tools are intended for educational and practice purposes only. They do not replace official FAA publications, ground instruction, or the judgment of a certificated flight instructor.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">3. Subscription and Billing</h2>
          <p>Access to the full Service requires a paid subscription. Plans are available on a monthly, 6-month, or annual basis at the prices displayed at checkout. Subscriptions renew automatically at the end of each billing period until canceled. You may cancel at any time through your account settings or App Store subscription settings. No refunds are issued for unused portions of a billing period.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">4. Account Responsibilities</h2>
          <p>You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You must provide accurate information when creating your account. Accounts are for individual use and may not be shared.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">5. Acceptable Use</h2>
          <p>You agree not to misuse the Service. Prohibited activities include attempting to reverse-engineer or scrape the Service, using automated tools to access the Service in ways that exceed normal usage, or using the Service for any unlawful purpose.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">6. Intellectual Property</h2>
          <p>All content, design, and software comprising the Service is owned by Flight Levels or its licensors and is protected by applicable intellectual property laws. You may not copy, reproduce, or distribute any part of the Service without written permission.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">7. Disclaimer of Warranties</h2>
          <p>The Service is provided "as is" without warranties of any kind. Flight Levels does not warrant that the Service will be uninterrupted, error-free, or that AI-generated content will be accurate or complete. Aviation training content generated by the Service should always be verified against official FAA sources.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">8. Limitation of Liability</h2>
          <p>To the maximum extent permitted by law, Flight Levels shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service. Our total liability for any claim shall not exceed the amount you paid for the Service in the three months preceding the claim.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">9. Changes to Terms</h2>
          <p>We may update these Terms from time to time. Continued use of the Service after changes are posted constitutes acceptance of the updated Terms. We will notify users of material changes via email or in-app notice.</p>
        </section>

        <section className="mb-8">
          <h2 className="text-xl font-semibold mb-3">10. Contact</h2>
          <p>Questions about these Terms may be directed to <a href="mailto:joe@flight-levels.com" className="text-blue-600 hover:underline">joe@flight-levels.com</a>.</p>
        </section>
      </main>
      <Footer />
    </>
  )
}
